# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PlanetProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.IntegerField(null=True)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_app.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=12)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('money', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=12)),
                ('how_many_space', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=12)),
                ('capacity', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_app.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='ShipProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_app.Product')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_app.Ship')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_app.Player')),
            ],
        ),
        migrations.AddField(
            model_name='ship',
            name='product',
            field=models.ManyToManyField(through='st_app.ShipProduct', to='st_app.Product'),
        ),
        migrations.AddField(
            model_name='player',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_app.Ship'),
        ),
        migrations.AddField(
            model_name='planetproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_app.Product'),
        ),
        migrations.AddField(
            model_name='planet',
            name='product',
            field=models.ManyToManyField(through='st_app.PlanetProduct', to='st_app.Product'),
        ),
    ]
