# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_app', '0002_auto_20170117_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=100),
        ),
    ]
