# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_app', '0003_event_eventeffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventeffect',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
