# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_app', '0003_auto_20170117_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_app.Product')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_app.Ship')),
            ],
        ),
        migrations.AddField(
            model_name='ship',
            name='product',
            field=models.ManyToManyField(through='st_app.ShipProduct', to='st_app.Product'),
        ),
    ]
