# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_app', '0004_eventeffect_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventeffect',
            name='money',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventeffect',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventeffect',
            name='stage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
