# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_app', '0005_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='planet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='st_app.Planet'),
            preserve_default=False,
        ),
    ]
