# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st_app', '0006_player_planet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='planet',
        ),
    ]
