# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_app', '0007_remove_player_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_app.Planet'),
        ),
    ]
